ProjectManagement/ProjectManagement/Controllers/PopUpController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectManagement.Entities;
using ProjectManagement.Models;

//Author             : Sahdan Hidayatul Muzaki
//Created date       : Kamis, 22/11/2018
//Modified by        : Sahdan Hidayatul Muzaki
//Date modified      : Jum'at, 23/11/2018
//Additional         : Method GetProjectByScheduleProject, Partial View
//Modified by        : Nispi Abdul Aziz
//Date modified      : Senin, 26/11/2018
//Additional         : Method SaveModul, SaveProject,PopUpAddModul, PopUpAddProject


namespace ProjectManagement.Controllers
{
    public class PopUpController : Controller
    {
        private ProjectManagementDBContext db = new ProjectManagementDBContext();
        // GET: Clients
        public ActionResult Index()
        {
            return View(db.ProjectSchedules.ToList());
        }

        public ActionResult PopUpProjectTimeline()
        {
            return View(db.ProjectTimelines.ToList());
        }

        public ActionResult PopUpAddModul()
        {
            Modul modul = db.Moduls.Find(1);
            ViewBag.ModulStatus = new SelectList(db.ModulStatus, "ModulStatusId", "Description");
            //ViewBag.ParentModulId = new SelectList(db.Moduls.Where(p => p.ProjectId == modul.ProjectId), "ModulId", "ModulName");
            ViewBag.ModulId = new SelectList(db.Moduls, "ModulId", "ModulName");
            //return View();
            return View(db.Projects.ToList());
        }

        public ActionResult PopUpAddRequirment()
        {
            Requirement req = db.Requirements.Find(1);
            // ViewBag.ModulStatus = new SelectList(db.ModulStatus, "ModulStatusId", "Description");
            //ViewBag.ParentModulId = new SelectList(db.Moduls.Where(p => p.ProjectId == modul.ProjectId), "ModulId", "ModulName");
            ViewBag.RequirmentTypeId = new SelectList(db.Requirements, "RequimentTypeId", "Description");
            //return View();
            return View(db.Requirements.ToList());
        }
        public JsonResult SaveModDoc(
            int idd,
            int id,
            string name,
            string file,
            string version)
        {
            var result = new jsonMessage();
            var Prodoc = db.ModulDocuments.Find(idd);
            Prodoc.DocumentTypeId = id;
            Prodoc.Version = version;
            Prodoc.DocumentName = name;
            Prodoc.FilePath = file;
            db.SaveChanges();
            result.Message = "UpdateBerhasil";
            return Json(result, JsonRequestBehavior.AllowGet);

        }
        public JsonResult SaveModul(
            int project,
            string ModulName,
            string ModulNumber,
            string ModulParent,
            string ModulPic,
            string ModulStatus,
            string maydays,
            string startDate,
            string EndDate
            )
        {
            var result = new jsonMessage();
            try
            {
                Modul mod = new Modul();
                mod.ProjectId = project;
                mod.ModulName = ModulName;
                mod.ModulNumber = ModulNumber;
                mod.ParentModulId = Convert.ToInt32(ModulParent);
                mod.PIC = ModulPic;
                mod.ModulStatusId = Convert.ToInt32(ModulStatus);
                mod.MadaysEstimation = Convert.ToDecimal(maydays);
                mod.StartDateActual = Convert.ToDateTime(startDate);
                mod.EndDateActual = Convert.ToDateTime(EndDate);
                //var z= db.Projects.Find(project);
                //z.StartDateActual = Convert.ToDateTime(startDate);
                db.Moduls.Add(mod);
                result.Message = "Data modul berhasil disimpan...";
                result.Status = true;
                db.SaveChanges();

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                result.Message = e + "Permintaan Anda tidak bisa diproses. Coba lagi nanti.";
                result.Status = false;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveProjectSchedule(int ProjectId, string Version, string StartDate, string EndDate, string CreatedDate, string CreatedBy)
        {
            var result = new jsonMessage();
            try
            {
                //define the model  
                ProjectSchedule newProjectSchedule = new ProjectSchedule();
                newProjectSchedule.ProjectScheduleId = 99;
                newProjectSchedule.ProjectId = ProjectId;
                newProjectSchedule.Version = Version;
                newProjectSchedule.StartDate = Convert.ToDateTime(StartDate);
                newProjectSchedule.EndDate = Convert.ToDateTime(EndDate);
                newProjectSchedule.CreatedDate = Convert.ToDateTime(CreatedDate);
                newProjectSchedule.CreatedBy = CreatedBy;
                newProjectSchedule.IsActive = true;


                //for insert recored..  
                db.ProjectSchedules.Add(newProjectSchedule);
                result.Message = "Data Schedule Project berhasil disimpan...";
                result.Status = true;

                db.SaveChanges();


            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                //ErrorLogers.ErrorLog(ex);
                result.Message = ex + "\nPermintaan Anda tidak bisa diproses. Coba lagi nanti.";
                result.Status = false;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveProjectTimeline(int ProjectScheduleId, int ProjectId, int ModulId, string StartDate, string EndDate, int? stUpdate, int idPT)
        {
            var result = new jsonMessage();
            try
            {
                if (stUpdate == 1)
                {
                    ProjectTimeline ubah = db.ProjectTimelines.Find(idPT);
                    ubah.StartDate = Convert.ToDateTime(StartDate);
                    ubah.EndDate = Convert.ToDateTime(EndDate);

                    result.Message = "Data Project Timeline berhasil diubah...";
                }
                else
                {
                    //define the model  
                    ProjectTimeline newProjectTimeline = new ProjectTimeline();
                    newProjectTimeline.ProjectScheduleId = ProjectScheduleId;
                    newProjectTimeline.ProjectId = ProjectId;
                    newProjectTimeline.ModulId = ModulId;
                    newProjectTimeline.StartDate = Convert.ToDateTime(StartDate);
                    newProjectTimeline.EndDate = Convert.ToDateTime(EndDate);

                    //for insert recored..  
                    db.ProjectTimelines.Add(newProjectTimeline);
                    result.Message = "Data Project Timeline berhasil disimpan...";
                }
                
                result.Status = true;

                db.SaveChanges();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                //ErrorLogers.ErrorLog(ex);
                result.Message = ex + "\nPermintaan Anda tidak bisa diproses. Coba lagi nanti.";
                result.Status = false;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveChangeRequest(int RequimentId,
            string ChangeRequestNumber,
            string Description,
            string MandaysEstimation)
        {
            var result = new jsonMessage();
            try
            {
                ChangeRequest changeRe = new ChangeRequest();
                changeRe.RequimentId = RequimentId;
                changeRe.ChangeRequestNumber = ChangeRequestNumber;
                changeRe.Description = Description;
                if (MandaysEstimation != "")
                {
                    changeRe.MandaysEstimation = Convert.ToDecimal(MandaysEstimation);
                }
                db.ChangeRequests.Add(changeRe);
                result.Message = "Tambah Berhasil";
                result.Status = true;
                db.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                result.Message = e + "Permintaan Anda tidak bisa diproses. Coba lagi nanti.";
                result.Status = false;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveRequirement(string ProjectId,
            string ModulId,
            string RequimentTypeId,
            string RequirementNumber,
            string Description,
            int Level)
        {
            var result = new jsonMessage();
            try
            {
                Requirement dataReq = new Requirement();
                dataReq.ProjectId = Convert.ToInt32(ProjectId);
                dataReq.ModulId = Convert.ToInt32(ModulId);
                dataReq.RequimentTypeId = Convert.ToInt32(RequimentTypeId);
                dataReq.RequirementNumber = RequirementNumber;
                dataReq.Description = Description;
                dataReq.Level = Level;
                result.Message = "Tambah Berhasil";
                result.Status = true;
                db.SaveChanges();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                result.Message = e + "Permintaan Anda tidak bisa diproses. Coba lagi nanti.";

ProjectManagement/ProjectManagement/Views/PopUp/GetProjectByScheduleProject.cshtml
@*
    Author             : Sahdan Hidayatul Muzaki
    Created date       : Jum'at, 23/11/2018
    Modified by        :
    Date modified      :
    Additional         :
*@

@model ProjectManagement.Entities.Project


@{
    Layout = null;

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />


    <!-- jQuery library -->
    <script src="code.jquery.com/jquery-1.12.4.js"></script>


    <!-- add thids links for the error message-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/1.3.1/css/toastr.css" />
    <script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/1.3.1/js/toastr.js"></script>



    <script>
        $(document).ready(function () {
        //________________________________________________________________

            $("#btnSave2").click(function () {
                var today = new Date();

                var day = today.getDate();
                var month = today.getMonth() + 1;
                var year = today.getFullYear();

                var strDate = year+"-"+month+"-"+day;

                var ProjectId = 8;
                var Version = $("#txtVersion").val();
                var StartDate = $("#txtStartDate").val();
                var EndDate = $("#txtEndDate").val();
                var CreatedDate = strDate;
                var CreatedBy = "Za-Q";

                //if (CheckRequiredFields()) {

                $('#dvLoader').show();
                $.ajax({
                    url: '@Url.Action("SaveProjectSchedule", "PopUp")',
                    type: 'POST',
                    data: JSON.stringify({ "ProjectId": ProjectId, "Version": Version, "StartDate": StartDate, "EndDate": EndDate, "CreatedDate": CreatedDate, "CreatedBy": CreatedBy }),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {
                        $('#dvLoader').hide();

                        if (result.Status == "True") {
                            toastr.success(result.Message);
                            clear();
                            //display();
                        }
                        else {
                            toastr.success(result.Message);
                            clear();
                            //display();

                        }
                    }
                });

                //}

            });

            $("#btnCancel").click(function () {
                clear();
            });

    });

        function CheckRequiredFields() {
            var isValid = true;
            $('.required').each(function () {
                if ($.trim($(this).val()) == '') {
                    isValid = false;
                    $(this).addClass('red_border');


                }
                else {
                    $(this).removeClass('red_border');

                }
            });
            return isValid;
        }

        function checkemail(valemail) {
            var forgetfilter = /^([\w-\.]+)@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
            if (forgetfilter.test(valemail)) {
                return true;
            }
            else {
                return false;
            }
        }
        function clear() {
            $("#txtVersion").val("");
            $("#txtStartDate").val("");
            $("#txtEndDate").val("");
            //$("#txtEmail").val("");
            //$('#btnSave').val("Save Client");
            //$("#hdnPID").val(0);
        }

        function isNumberKey(evt) {
            var charcode = (evt.which) ? evt.which : evt.keycode
            if (charcode > 31 && (charcode < 48 || charcode > 58)
                && evt.keyCode != 35 && evt.keyCode != 36 && evt.keyCode != 37
                && evt.keyCode != 38 && evt.keyCode != 39 && evt.keyCode != 40
                && evt.keyCode != 46) {
                return false;
            }
            else {
                return true;
            }
        }
    </script>
</head>
<body>
    <div id="dvLoader" class="LoadingDiv" style="display: none;">
        <table style="height: 100%; margin: auto;">
            <tr>
                <td style="vertical-align: middle;">
                    <center>
                        <img src="http://www.girlsgotit.org/images/form-loader.gif" alt="Loading" />
                    </center>
                </td>
            </tr>
        </table>
    </div>


    <!--
        <button class="btn btn-success btn-lg" data-toggle="modal" data-target="#modalForm">
            Create New Project Schedule
        </button>
    -->
    <!-- Modal -->
    <div class="modal fade" id="modalForm222" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Tutup</span>
                    </button>
                    <h4 class="modal-title" id="labelModalKu">Insert Project Schedule</h4>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">
                    <p class="statusMsg"></p>
                    <form role="form">
                        <div class="form-group">
                            <label for="">Project Name</label>
                            <input type="text" class="form-control" id="txtProjectName" placeholder="(Nama Project)" value="@Html.DisplayFor(model => model.ProjectName)" />
                        </div>
                        <div class="form-group">
                            <label for="">Version</label>
                            <input type="text" class="form-control" id="txtVersion" placeholder="Masukkan Version" />
                        </div>
                        <div class="form-group">
                            <label for="">Start Date</label>
                            <input type="date" class="form-control" id="txtStartDate" placeholder="Masukkan Start Date" />
                        </div>
                        <div class="form-group">
                            <label for="">End Date</label>
                            <input type="date" class="form-control" id="txtEndDate" placeholder="Masukkan End Date" />
                        </div>
                    </form>
                </div>
                <input id="txtNamaFromDb" type="hidden" value="" />
                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    <!--button type="submit" class="btn btn-primary submitBtn">Save</!--button>  -->
                    <input id="btnSave2" class="btn btn-primary submitBtn" type="button" value="Save Schedule Project" />
                </div>
            </div>
        </div>
    </div>
</body>
</html>

ProjectManagement/ProjectManagement/Views/PopUp/Index.cshtml
@*
    Author             : Sahdan Hidayatul Muzaki
    Created date       : Kamis, 22/11/2018
    Modified by        : Sahdan Hidayatul Muzaki
    Date modified      : Jum'at, 23/11/2018
    Additional         : Anchor/Partial View
    Modified by        : Sahdan Hidayatul Muzaki
    Date modified      : Selasa, 04/12/2018
    Additional         : Get Data By ID for View (hardcode)
*@
@using System.Linq
@using ProjectManagement.Entities


@{
    ViewBag.Title = "Index";
    Layout = null;
}

@{
    ProjectManagementDBContext db = new ProjectManagementDBContext();
    var projectById = db.Projects.Find(3);

    var projectScheduleById = db.ProjectSchedules.Find(5);
    var modulById = db.Moduls.Find(3);
}

@*                                        *@
@*                                        *@
@*                         <script src="~/Scripts/bootstrap.js"></script>               *@
<head>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />


    <!-- jQuery library -->
    <script src="code.jquery.com/jquery-1.12.4.js"></script>


    <!-- add thids links for the error message-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/1.3.1/css/toastr.css" />
    <script src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/1.3.1/js/toastr.js"></script>




    <script>
        $(document).ready(function () {
        //________________________________________________________________

            $("#btnSave2").click(function () {
                var today = new Date();

                var day = today.getDate();
                var month = today.getMonth() + 1;
                var year = today.getFullYear();

                var strDate = year+"-"+month+"-"+day;

                var ProjectId = $("#txtIdFromDb").val();
                var Version = $("#txtVersion").val();
                var StartDate = $("#txtStartDate").val();
                var EndDate = $("#txtEndDate").val();
                var CreatedDate = strDate;
                var CreatedBy = "-";

                //if (CheckRequiredFields()) {

                $('#dvLoader').show();
                $.ajax({
                    url: '@Url.Action("SaveProjectSchedule", "PopUp")',
                    type: 'POST',
                    data: JSON.stringify({ "ProjectId": ProjectId, "Version": Version, "StartDate": StartDate, "EndDate": EndDate, "CreatedDate": CreatedDate, "CreatedBy": CreatedBy }),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (result) {
                        $('#dvLoader').hide();

                        if (result.Status == "True") {
                            toastr.success(result.Message);
                            clear();
                            //display();
                        }
                        else {
                            toastr.success(result.Message);
                            clear();
                            //display();

                        }
                    }
                });

                //}

            });

            $("#btnCancel").click(function () {
                clear();
            });

    });

        function CheckRequiredFields() {
            var isValid = true;
            $('.required').each(function () {
                if ($.trim($(this).val()) == '') {
                    isValid = false;
                    $(this).addClass('red_border');


                }
                else {
                    $(this).removeClass('red_border');

                }
            });
            return isValid;
        }

        function checkemail(valemail) {
            var forgetfilter = /^([\w-\.]+)@@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
            if (forgetfilter.test(valemail)) {
                return true;
            }
            else {
                return false;
            }
        }
        function clear() {
            $("#txtVersion").val("");
            $("#txtStartDate").val("");
            $("#txtEndDate").val("");
            //$("#txtEmail").val("");
            //$('#btnSave').val("Save Client");
            //$("#hdnPID").val(0);
        }

        function isNumberKey(evt) {
            var charcode = (evt.which) ? evt.which : evt.keycode
            if (charcode > 31 && (charcode < 48 || charcode > 58)
                && evt.keyCode != 35 && evt.keyCode != 36 && evt.keyCode != 37
                && evt.keyCode != 38 && evt.keyCode != 39 && evt.keyCode != 40
                && evt.keyCode != 46) {
                return false;
            }
            else {
                return true;
            }
        }


        var TeamDetailPostBackURL = '/PopUp/GetProjectByScheduleProject';
        $(function () {
            $(".anchorDetail").click(function () {
                debugger;
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                var options = { "backdrop": "static", keyboard: true };
                $.ajax({
                    type: "GET",
                    //url: TeamDetailPostBackURL,
                    //INI MEMANGGIL METHOD DI CONTROLLER
                    url: "/PopUp/GetProjectByScheduleProject",
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        debugger;
                        $('#myModalContent').html(data);
                        $('#modalForm').modal(options);
                        $('#modalForm').modal('show');

                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            //$("#closebtn").on('click',function(){
            //    $('#modalForm').modal('hide');

            $("#closbtn").click(function () {
                $('#modalForm').modal('hide');
            });
        });


    </script>


    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>

@*____________________________________________________________________________________________*@

@*

    @section scripts
    {
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


        <script>
            var TeamDetailPostBackURL = '/PopUp/GetProjectByScheduleProject';
            $(function () {
                $(".anchorDetail").click(function () {
                    debugger;
                    var $buttonClicked = $(this);
                    var id = $buttonClicked.attr('data-id');
                    var options = { "backdrop": "static", keyboard: true };
                    $.ajax({
                        type: "GET",
                        url: TeamDetailPostBackURL,
                        contentType: "application/json; charset=utf-8",
                        data: { "Id": id },
                        datatype: "json",
                        success: function (data) {
                            debugger;
                            $('#myModalContent').html(data);
                            $('#modalForm').modal(options);
                            $('#modalForm').modal('show');

                        },
                        error: function () {
                            alert("Dynamic content load failed.");
                        }
                    });
                });
                //$("#closebtn").on('click',function(){
                //    $('#modalForm').modal('hide');

                $("#closbtn").click(function () {
                    $('#modalForm').modal('hide');
                });
            });

        </script>

    } *@


@*____________________________________________________________________________________________*@
<a href="javascript:void(0);" class="anchorDetail" data-id="8">Project Schedule</a>



<div id="dvLoader" class="LoadingDiv" style="display: none;">
    <table style="height: 100%; margin: auto;">
        <tr>
            <td style="vertical-align: middle;">
                <center>
                    <img src="http://www.girlsgotit.org/images/form-loader.gif" alt="Loading" />
                </center>
            </td>
        </tr>
    </table>
</div>


<!--
    <button class="btn btn-success btn-lg" data-toggle="modal" data-target="#modalForm">
        Create New Project Schedule
    </button>
-->
<!-- Modal -->
<div class="modal fade" id="modalForm" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Tutup</span>
                </button>
                <h4 class="modal-title" id="labelModalKu">Insert Project Schedule</h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body">
                <p class="statusMsg"></p>
                <form role="form">
                    <div class="form-group">
                        <label for="">Project Name</label>
                        <input type="text" class="form-control" id="txtProjectName" placeholder="(Nama Project)" value="@projectById.ProjectName" />
                    </div>
                    <div class="form-group">
                        <label for="">Version</label>
                        <input type="text" class="form-control" id="txtVersion" placeholder="Masukkan Version" />
                    </div>
                    <div class="form-group">
                        <label for="">Start Date</label>
                        <input type="date" class="form-control" id="txtStartDate" placeholder="Masukkan Start Date" />
                    </div>
                    <div class="form-group">
                        <label for="">End Date</label>
                        <input type="date" class="form-control" id="txtEndDate" placeholder="Masukkan End Date" />
                    </div>
                    <input id="txtNamaFromDb" type="hidden" value="@projectById.ProjectName" />
                    <input id="txtIdFromDb" type="hidden" value="@projectById.ProjectId" />
                </form>
            </div>

            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                <!--button type="submit" class="btn btn-primary submitBtn">Save</!--button>  -->
                <input id="btnSave2" class="btn btn-primary submitBtn" type="button" value="Save Schedule Project" />
            </div>
        </div>
    </div>
</div>



@*____________________________________________________________________________________________*@
